name: foodcast
channels:
    - defaults
    - conda-forge
dependencies:
    - cloudpickle=1.3.0
    - click=7.0
    - flake8=3.7.8
    - ipykernel=5.1.2
    - jupyter=1.0.0
    - jupytext=1.4.0
    - mlflow=1.8.0
    - mypy=0.770
    - numpy=1.17.4
    - pandas=0.25.1
    - plotly=4.5.4
    - pytest=5.2.1
    - pytest-cov=2.8.1
    - python=3.7.6
    - python-dotenv=0.10.3
    - scikit-learn=0.21.3
